Feature/custom keycloak (#2)
* add dockerfile with custom theme

* add realm import

* update changelog

* update realm

* update realm

* add display name for realm

* update readme

* activate two factor authentication

* Refactor

* Fix pipeline build

* Fix pipeline build

* Fix Dockerfile

* Add gitignore

---------

Co-authored-by: Oriol Canadés <oriol.canades@in2.es>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,6 @@ on:
   pull_request:
     types: [opened, synchronize, reopened]
 
-
 jobs:
 
   sonarcloud:
@@ -17,6 +16,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
@@ -25,7 +25,7 @@ jobs:
 
   deploy-test:
     name: deploy-test
-    needs: build
+    needs: sonarcloud
     if: success()
     runs-on: ubuntu-latest
     environment: test
@@ -37,6 +37,26 @@ jobs:
       - name: Build and Push docker image
         run: |
           IMAGE_TAG="$PROJECT_NAME:v$VERSION$SUFFIX"
+          echo "DOCKER_HUB_CLIENT_NAME: $DOCKER_HUB_CLIENT_NAME"
+          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
+          echo "PROJECT_NAME: $PROJECT_NAME"
+          echo "VERSION: $VERSION"
+          echo "SUFFIX: $SUFFIX"
+            
+            if [ -z "$DOCKER_HUB_CLIENT_NAME" ]; then
+          echo "Error: DOCKER_HUB_CLIENT_NAME is not set."
+            exit 1
+            fi
+            
+            if [ -z "$DOCKER_USERNAME" ]; then
+          echo "Error: DOCKER_USERNAME is not set."
+            exit 1
+            fi
+            
+            if [ -z "$DOCKER_PASSWORD" ]; then
+          echo "Error: DOCKER_PASSWORD is not set."
+            exit 1
+            fi
           docker build --file Dockerfile --build-arg SKIP_TESTS=true --tag $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG .
           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
           docker push $DOCKER_HUB_CLIENT_NAME/$IMAGE_TAG
